include:
  - board: nice_nano_v2
    shield: wired_split_funda
  
  # Ejemplo de más shields o boards:
  # - board: nice_nano_v2
  #   shield: wired_split_funda_left
  # - board: nice_nano_v2
  #   shield: wired_split_funda_right